### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by misleadingname** [BnuuySolutions/OculusWRP#1]
I'm trying to setup OculusWRP on a fresh install of Windows 10 (21H2 19044.3324), without the actual Oculus runtime, drivers or app installed. After installing SteamVR and compiling a release build of OculusWRP for x64, I see that OculusWRP does initialize and pick up the HMD and both controllers. Unfortunately there's nothing on the HMD itself; There's no display output while this is being put in the SteamVR Console.

```
[Info] - oculuswrp: HMD has been put into standby.
```
In conjuction with:
```
[Status Alert] SteamVR Fail (422)
```

I did reseat the USB, plug it into different ports and reseat the HDMI. Although, I might be doing something wrong but also it could be plain incompatibility with my setup.

**Comment by whatdahopper** [comment]
Did you read the GitHub? This is nowhere near production-level code, it barely even works, it is not daily driver-able at all due to no distortion matrix and no controller state other than poses. Not only that, you need Oculus drivers and a copy of the `Rift.dll` library from the Oculus runtime, and not just any drivers or runtime, you need a very specific one which I have linked below.

You can get both the drivers and runtime from these links, please only use the ones I have linked, otherwise you'll have issues:
- [Oculus Runtime](https://securecdn.oculus.com/binaries/download/?id=3031299280335544)
- [Oculus Drivers](https://securecdn.oculus.com/binaries/download/?id=3653357211466543)

Again, do not try to use a `Rift.dll` or drivers from newer or older Oculus runtime/driver packages, ***YOU MUST GRAB THEM FROM THE SPECIFIC PACKAGE VERSIONS I LINKED, DUE TO VTABLE MESS.***

Note that after installing the drivers and obtaining `Rift.dll` from the runtime package you downloaded, you'll have to update the DLL path in the code as I haven't setup proper DLL loading yet.

Bare in mind, none of this is actually supported until I feel like it is ready for prime time and I make a release. While I have no problem with people testing and compiling this on their own, my hope is that they at least know what they're getting themselves into.

I will not accept issues going forward if people can't read the README, this is just a huge PoC at the moment and not really ready for people to sit down and test for themselves on a public scale, which is why I was hesitant about releasing this code in its current state.

Finally, I recommend [joining my Discord](https://discord.gg/dPsfJhsGwb) so you don't clutter up my GitHub issues, especially since I don't want to give proper support for issues at this time and so you get updates as to what I am doing.

**Comment by misleadingname** [comment]
Appreciate the response.

Don't worry, I'm well aware that this is very far away from being usable, I just wanted to try to set it up and benchmark the performance difference between using a custom runtime, and the native oculus one.
